// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/maxshearer/max.shearer.co/frontend/components"
	"github.com/maxshearer/max.shearer.co/frontend/layouts"
)

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"index\"><div class=\"content\"><h1>Making nice things for mobile and the web. Currently building <a href=\"https://waywi.se\">Waywise</a>.</h1><p>I'm a designer and developer with 20 years of experience building for web and mobile. My current work focuses on building applications with Svelte, React Native/Expo, Go, and PostgreSQL.</p><p>Day-to-day I lead the team building interfaces at <a href=\"https://www.caura.com\" rel=\"nofollow\">Caura</a>, an automotive tech business taking the hassle out of motoring admin.</p><p>In my spare time I&rsquo;m building Waywise, an AI-generated travel guidebook for iOS to allow travellers to explore cities in a more personal and socially responsible way.</p></div><section class=\"work\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.WorkItem(components.WorkItemProps{
				ID:       "waywise",
				Label:    "Waywise: an AI-generated travel guidebook for iOS",
				Filename: "waywise",
				Width:    1000,
				Height:   600,
				AltText:  "Three mobile phone mockups with Waywise travel app displayed",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.WorkItem(components.WorkItemProps{
				ID:       "yard-poker",
				Label:    "Yard Poker: texas hold&rsquo;em poker app for friends",
				Filename: "yard-poker",
				Width:    1000,
				Height:   600,
				AltText:  "Mockup of a laptop displaying the Yard Poker web app",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.WorkItem(components.WorkItemProps{
				ID:       "think-shape",
				Label:    "Think Shape: fashion app empowering people to buy less and buy better",
				Filename: "think-shape",
				Width:    1000,
				Height:   600,
				AltText:  "Scattered iPhone mockups displaying various screens of the Think Shape app",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.WorkItem(components.WorkItemProps{
				ID:       "tradegraft",
				Label:    "Tradegraft: connecting construction sites with verified operators",
				Filename: "tradegraft",
				Width:    1000,
				Height:   600,
				AltText:  "Mockup of a laptop displaying the Tradegraft platform¥",
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</section></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Default(layouts.LayoutProps{
			PageID: "index",
			Stylesheets: []string{
				"index.css",
			},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
